apiVersion : apps/v1
kind: Deployment
metadata:
  name: mokhosgsspringboot 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mokhosgsspringboot
  template:
    metadata:
      labels:
        app: mokhosgsspringboot 
    spec:
      containers:
        - name: mokhosgsspringboot 
          image: mokhoregistry.azurecr.io/mokhosgsspringboot
          ports:
          - containerPort: 8080